### ISSUE TITLE
touch gesture interpreted by OS during drag

### ISSUE THREAD

**Issue by pslavers** [marcojakob/dart-dnd#24]
Firstly, thanks for a great library.
I am trying to do DnD on touch devices.
However, the drag gesture also has an effect on the whole page.
Using your example:
https://github.com/marcojakob/dart-dnd/tree/master/example/basic
On an iPhone or iPad while dragging the paper (which becomes a face) the whole page moves.

Do you know how to stop this?

Finally, you library is the only one I could get to work with the Chrome Developer Tools Touch mode!!
Cheers,
Phil.

**Comment by marcojakob** [comment]
Are you building the examples from source? The examples on the
code.makery.ch website are not yet the latest version (I will need to
update this).

If it doesn't work with the newest version I'd guess the problem is
something with preventDefault. I don't have an Apple-Touch device but I
might be able to help a bit more next week after my vacation.

**Comment by pslavers** [comment]
I have recompiled after doing an 'upgrade dependencies'.
If works perfectly on: - Chrome on an iPhone. - Chrome on an iPad - Safari on an iPhone
it does not work on: - Safari on an iPad.
However, I believe the issue is a Safari version issue, not a dnd issue.
Thanks for your help, sorry to have wasted your time.
I will close the issue.

**Comment by marcojakob** [comment]
Thanks @pslavers for reporting and testing it on the various devices.
